services:
  mysql:
    image: mysql:8
    container_name: sparta-crud-mysql
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=test
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "bash", "-lc", "mysqladmin ping -h 127.0.0.1 -prootpasswd || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5